---
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_file = "useful_R_functions.pdf") })
output:
  pdf_document:
    extra_dependencies: ["booktabs"]
    includes: 
      before_body: "Chapters/assets/title.sty"
    latex_engine: xelatex
    number_sections: true
    toc_depth: 3
    highlight: "Chapters/assets/arrow.theme"
urlcolor: blue
linkcolor: black
--- 
\aboverulesep=0ex
\belowrulesep=0ex
\tableofcontents
\listoftables
\listoffigures
\newpage

```{r "setup", message = FALSE , warning = FALSE}
# Loading required libraries
if (!requireNamespace("here"))
  stop('

  HOLD ON!
  YOU NEED TO INSTALL THE PACKAGE "here":
  Try Using install.packages("here")
  ')
library(knitr)
library(kableExtra)
library(RColorBrewer)
library(UsingR)
library(ggplot2)
```

```{r child = here::here("Chapters","01_basic_probability_and_tricks.Rmd")}
```

```{r child = here::here("Chapters","02_random_variables_simulation.Rmd")}
```

```{r child = here::here("Chapters","03_expectation_variance.Rmd")}
```

```{r child = here::here("Chapters","04_joint_independence.Rmd")}
```

```{r child = here::here("Chapters","05_covariance_correlation.Rmd")}
```

```{r child = here::here("Chapters","06_computations_random_variables.Rmd")}
```

```{r child = here::here("Chapters","07_large_numbers_central_limit.Rmd")}
```

```{r child = here::here("Chapters","08_exploratory_graphical.Rmd")}
```

```{r child = here::here("Chapters","09_exploratory_numerical.Rmd")}
```

```{r child = here::here("Chapters","10_statistical_models.Rmd")}
```

```{r child = here::here("Chapters","11_bootstrapping.Rmd")}
```

```{r child = here::here("Chapters","12_unbiased_estimator.Rmd")}
```

```{r child = here::here("Chapters","13_maximum_likelihood.Rmd")}
```
